// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtcjeducwimcqqujnwkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10Y2plZHVjd2ltY3FxdWpud2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTIzOTcsImV4cCI6MjA3MTA2ODM5N30.P-9OFFxJpHNizvFEHQifTwpj4jAkV17YUL9hkMTaFmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});